### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by meneal**
To mitigate https://twitter.com/peter_szilagyi/status/1437646118700175360

### CODE REVIEW

**Comment by meneal** [comment]
@shawnzhu could use a bit of help if you have the time. This breaks [here](https://github.com/IBM/docker-hive/runs/3603697851?check_suite_focus=true#step:5:36). I needed to update the paths to the hadoop and hive packages and seemingly the underlying directory structure has changed. I can't seem to find any jars in the new structure at all.

**Review by apreethi13 — COMMENTED** [review]
Changes looks good.. is this [Makefile](https://github.com/IBM/docker-hive/blob/main/Makefile) obsolete now, if so can this be delted ?

**Comment by meneal** [comment]
>is this Makefile obsolete now, if so can this be delted ?

No, the `Makefile` is still of use should someone want to build/test locally.

**Review by apreethi13 — APPROVED** [review]
lgtm 👍

**Review by justineyster — APPROVED** [review]
LGTM!

**Review by shawnzhu — APPROVED** [review]

**Review by shawnzhu — APPROVED** [review]

**Pull request merged**
